/**
 * brand-config.js — Trilingual brand configuration for MED&გზური / MedPath / МедПуть
 * Each language has its own visual identity, tone, and content.
 */
const brandConfig = {
  ka: {
    name: "Med&გზური",
    tagline: "ვპოულობთ გზას შენი შვილის მკურნალობისკენ",
    taglineSub: "სამედიცინო ნავიგაცია ოჯახებისთვის",
    colors: {
      primary: "#8B1A1A",
      primaryHover: "#6B1414",
      accent: "#D4A843",
      accentHover: "#B8922E",
      bg: "#FFFDF7",
      surface: "#F5F0E8",
      text: "#2C1810",
      textMuted: "#6B5D52",
      border: "#D9CFC2",
      hero: "linear-gradient(135deg, #8B1A1A 0%, #5C1010 50%, #2C1810 100%)",
    },
    fonts: {
      heading: "'BPG Nino Mtavruli', 'Noto Sans Georgian', sans-serif",
      body: "'Noto Sans Georgian', sans-serif",
    },
    cta: {
      primary: "დაიწყე ახლა",
      secondary: "გაიგე მეტი",
      contact: "დაგვიკავშირდი",
    },
    hero: {
      badge: "სამედიცინო ნავიგაცია",
      headline: "ექიმი ამბობს \u201Eვერაფერს ვიზამთ\u201C?\nჩვენ ვიცით სად მივმართოთ.",
      sub: "50+ მიმართვა. 12+ პროგრამა. 3 კონტინენტი. რეალური გამოცდილება.",
      btnPrimary: "დაიწყე ახლა",
      btnSecondary: "გაიგე მეტი",
      stats: [
        { number: "50+", label: "მიმართვა" },
        { number: "12+", label: "პროგრამა" },
        { number: "3", label: "კონტინენტი" },
      ],
    },
    values: [
      { icon: "🌍", title: "ენის ბარიერი აღარ არსებობს", desc: "38 მილიონი სამედიცინო კვლევა ახლა ქართულად ხელმისაწვდომია" },
      { icon: "🔍", title: "იპოვე ის, რაც Google-ში ვერ იპოვე", desc: "PubMed, კლინიკური კვლევები, ევროპული კლინიკები — ერთი ძიებით" },
      { icon: "💰", title: "₾149-დან — არა ათასობით ლარი", desc: "საერთაშორისო დონის ინფორმაცია, ქართული ფასით" },
    ],
    services: {
      label: "სერვისები",
      title: "რას გთავაზობთ",
      subtitle: "აირჩიეთ თქვენზე მორგებული სერვისი — ძიებიდან სრულ კოორდინაციამდე",
      items: [
        { icon: "📦", title: "ტულკითი", price: "₾149", desc: "ელ-ფოსტის შაბლონები, კვლევების ძიების ინსტრუქცია, კონტაქტების ტრეკერი" },
        { icon: "🤖", title: "AI ნავიგატორი", price: "₾497/თვე", desc: "კლინიკური კვლევების მოძიება, შესაბამისობის შემოწმება, ელ-ფოსტის გენერაცია" },
        { icon: "🌐", title: "პირადი ნავიგაცია", price: "₾5,000+", desc: "სრული პერსონალური მომსახურება — ძიება, კომუნიკაცია, ლოჯისტიკა" },
      ],
    },
    steps: {
      label: "პროცესი",
      title: "სამი მარტივი ნაბიჯი",
      subtitle: "დაიწყეთ დღეს და 24 საათში მიიღეთ პირველი შედეგები",
      items: [
        { title: "მოგვიყევით", desc: "შეავსეთ მოკლე ანკეტა — დიაგნოზი, ასაკი, რა სცადეთ" },
        { title: "ჩვენ ვეძებთ", desc: "AI + ექსპერტი ეძებს კვლევებს, პროგრამებს, კლინიკებს 3 კონტინენტზე" },
        { title: "მიიღეთ გეგმა", desc: "პერსონალიზებული ანგარიში: ვარიანტები, ფასები, შემდეგი ნაბიჯები" },
      ],
    },
    trust: "95-დღიანი კამპანია • 50+ მიმართვა • 24% წარმატების მაჩვენებელი",
    contact: {
      label: "კონტაქტი",
      title: "დაიწყეთ ძიება დღეს",
      description: "მოგვწერეთ და დაგეხმარებით თქვენთვის სწორი სერვისის შერჩევაში",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Messenger",
      linkWhatsapp: "995555145719",
      linkFacebook: "61587738421431",
      form: {
        name: "სახელი *",
        namePlaceholder: "თქვენი სახელი",
        phone: "ტელეფონი *",
        phonePlaceholder: "+995 5XX XXX XXX",
        email: "ელ-ფოსტა",
        emailPlaceholder: "your@email.com",
        message: "შეტყობინება *",
        messagePlaceholder: "მოგვიყევით თქვენი კითხვა...",
        submit: "📨 გაგზავნა",
        successTitle: "გმადლობთ!",
        successText: "თქვენი შეტყობინება მიღებულია.",
      },
    },
    nav: {
      search: "ძიება",
      services: "სერვისები",
      process: "პროცესი",
      contact: "კონტაქტი",
      intake: "ანკეტა",
      searchPlaceholder: "ძიება აქტიურია",
    },
    searchQueries: [
      "ფილტვის კიბოს მკურნალობა",
      "II ტიპის დიაბეტის კვლევები",
      "ჰიპერტენზიის თანამედროვე მიდგომები",
      "ონკოლოგიური კლინიკები ევროპაში",
      "ეპილეფსიის ახალი პრეპარატები",
      "კარდიოლოგიური რეაბილიტაცია",
    ],
    footer: {
      copyright: "© 2026 Med&გზური",
      disclaimer: "ეს არის საინფორმაციო სერვისი და არ წარმოადგენს სამედიცინო კონსულტაციას. ყველა გადაწყვეტილება მიიღეთ მკურნალ ექიმთან ერთად.",
    },
    social: {
      telegram: "https://t.me/medgzuri",
      facebook: "https://facebook.com/medgzuri",
    },
    locale: "ka-GE",
    dir: "ltr",
    intake: {
      pageTitle: "უფასო კონსულტაცია",
      badge: "უფასო აქცია · 10 დღე",
      steps: [
        { id: "intro", label: "დასაწყისი" },
        { id: "child", label: "ბავშვი" },
        { id: "medical", label: "დიაგნოზი" },
        { id: "goals", label: "მიზნები" },
        { id: "survey", label: "გამოკითხვა" },
        { id: "contact", label: "კონტაქტი" },
        { id: "done", label: "მზადაა" },
      ],
      progress: { step: "ნაბიჯი", of: "-დან" },
      nav: { back: "← უკან", next: "შემდეგი →", start: "შევსების დაწყება →", submit: "გაგზავნა ✓" },
      intro: {
        title: "ვიპოვით კლინიკურ კვლევებს თქვენი შვილისთვის",
        desc: "შეავსეთ ანკეტა 3 წუთში — ჩვენ უფასოდ შევარჩევთ შესაფერის სამკურნალო პროგრამებსა და კვლევებს მსოფლიო მასშტაბით",
        howTitle: "როგორ მუშაობს:",
        howSteps: "1. ავსებთ ანკეტას ბავშვის შესახებ (3 წუთი)\n2. ჩვენ ვარჩევთ შესაფერის კვლევებს (1-3 დღე)\n3. იღებთ სიას აღწერილობით თქვენს ენაზე",
        howNote: "დაფუძნებულია რეალურ გამოცდილებაზე — 7 თვის ნავიგაცია აშშ-ისა და ევროპის კლინიკებში",
        stats: [
          { n: "50+", t: "მიმართვა ექიმებთან" },
          { n: "12+", t: "ნაპოვნი პროგრამა" },
          { n: "24%", t: "წარმატების მაჩვენებელი" },
        ],
      },
      child: {
        title: "თქვენი ბავშვის შესახებ",
        subtitle: "ძირითადი ინფორმაცია კვლევების შესარჩევად",
        nameLabel: "ბავშვის სახელი (არასავალდებულო)",
        namePlaceholder: "სახელი",
        ageLabel: "ბავშვის ასაკი *",
        ageUnits: ["თვე", "წელი"],
        countryLabel: "საცხოვრებელი ქვეყანა *",
        countries: ["საქართველო", "თურქეთი", "გერმანია", "ისრაელი", "აშშ", "საფრანგეთი", "იტალია", "ესპანეთი", "სხვა ქვეყანა"],
        otherCountryPlaceholder: "მიუთითეთ ქვეყანა",
      },
      diagnosis: {
        title: "დიაგნოზი",
        subtitle: "აირჩიეთ ერთი ან რამდენიმე",
        items: [
          { id: "cp", label: "ცერებრალური დამბლა (CP)" },
          { id: "hie", label: "ჰიპოქსიურ-იშემიური ენცეფალოპათია (HIE)" },
          { id: "epilepsy", label: "ეპილეფსია" },
          { id: "genetic", label: "გენეტიკური დაავადება" },
          { id: "oncology", label: "ონკოლოგია (ბავშვთა)" },
          { id: "cardiology", label: "კარდიოლოგია (თანდაყოლილი გულის მანკი)" },
          { id: "rare", label: "იშვიათი (ორფანული) დაავადება" },
          { id: "neuromuscular", label: "ნეირომუსკულარული დაავადება (SMA, DMD)" },
          { id: "autism", label: "აუტიზმი / აუტისტური სპექტრის აშლილობა" },
          { id: "other", label: "სხვა" },
        ],
        otherPlaceholder: "მიუთითეთ დიაგნოზი",
        detailsLabel: "ბავშვის მდგომარეობის მოკლე აღწერა",
        detailsPlaceholder: "მაგ.: ბავშვი ვერ იჭერს თავს, აქვს კრუნჩხვები, MRI აჩვენა...",
        treatmentLabel: "რა მკურნალობა სცადეთ?",
        treatmentPlaceholder: "რეაბილიტაცია, წამლები, ოპერაციები...",
        mriLabel: "თავის ტვინის MRI შედეგები გაქვთ?",
        mriOptions: ["დიახ", "არა", "არ ვიცი"],
      },
      goals: {
        title: "რას ეძებთ?",
        subtitle: "აირჩიეთ ყველა აქტუალური",
        items: [
          { id: "clinical_trials", label: "კლინიკური კვლევის პოვნა (უფასო მკურნალობა)" },
          { id: "rehab", label: "სპეციალიზებული რეაბილიტაციის ცენტრის პოვნა" },
          { id: "second_opinion", label: "უცხოელი ექიმის მეორე აზრის მიღება" },
          { id: "experimental", label: "ექსპერიმენტული თერაპიის პოვნა (ღეროვანი უჯრედები და სხვ.)" },
          { id: "financial", label: "ფინანსური დახმარების / გრანტების პოვნა" },
          { id: "documents", label: "დოკუმენტებისა და კომუნიკაციის დახმარება ინგლისურად" },
          { id: "travel", label: "მკურნალობაზე მგზავრობის ორგანიზება" },
        ],
        otherLabel: "სხვა რამ? (არასავალდებულო)",
        otherPlaceholder: "სხვა საჭიროებები...",
      },
      survey: {
        title: "ერთი შეკითხვა",
        subtitle: "დაგვეხმარეთ ამ სერვისის ღირებულების გაგებაში",
        question: "წარმოიდგინეთ, რომ სპეციალისტი პოულობს თქვენი შვილისთვის შესაფერის კლინიკურ კვლევებს, ამზადებს სამედიცინო დოკუმენტებს ინგლისურად, წერს წერილებს ექიმებს და ახლავს მთელ კომუნიკაციის პროცესს. რამდენს გადაიხდიდით ასეთ სერვისში?",
        ranges: [
          { value: "0", label: "უფასოდ (არ ვარ მზად გადახდისთვის)" },
          { value: "50-150", label: "₾150 – ₾400" },
          { value: "150-500", label: "₾400 – ₾1 300" },
          { value: "500-1000", label: "₾1 300 – ₾2 700" },
          { value: "1000-3000", label: "₾2 700 – ₾8 000" },
          { value: "3000+", label: "₾8 000+" },
        ],
        valueLabel: "რა იქნებოდა ყველაზე ღირებული თქვენთვის? (არასავალდებულო)",
        valuePlaceholder: "მაგ.: დოკუმენტების თარგმნის დახმარება, გრანტების ძიება, ექიმებთან კავშირი...",
        sourceLabel: "როგორ შეიტყვეთ Med&გზური-ს შესახებ?",
        sources: ["Facebook", "Instagram", "YouTube", "მეგობრები/ნაცნობები", "Google ძიება", "სხვა"],
      },
      contact: {
        title: "საკონტაქტო მონაცემები",
        subtitle: "სად გამოგიგზავნოთ შედეგები?",
        nameLabel: "თქვენი სახელი *",
        namePlaceholder: "სახელი და გვარი",
        emailLabel: "ელ-ფოსტა",
        emailPlaceholder: "email@example.com",
        phoneLabel: "ტელეფონი (WhatsApp)",
        phonePlaceholder: "+995...",
        messengerLabel: "Messenger / Facebook",
        messengerPlaceholder: "Facebook პროფილის ბმული ან სახელი",
        preferLabel: "სასურველი კომუნიკაციის საშუალება",
        preferOptions: [
          { v: "whatsapp", l: "WhatsApp" },
          { v: "messenger", l: "Messenger" },
          { v: "email", l: "Email" },
        ],
        consent: "ვეთანხმები მონაცემების დამუშავებას კლინიკური კვლევების შერჩევის მიზნით. მონაცემები გამოიყენება მხოლოდ ამ მიზნისთვის და არ გადაეცემა მესამე პირებს. *",
      },
      done: {
        title: "განაცხადი გაგზავნილია!",
        message: "ჩვენ შევარჩევთ შესაფერის კლინიკურ კვლევებსა და პროგრამებს 1-3 სამუშაო დღეში და დაგიკავშირდებით",
        nextTitle: "რა იქნება შემდეგ:",
        nextSteps: "1. ჩვენი სპეციალისტი შეისწავლის თქვენს ანკეტას\n2. ჩაატარებს ძიებას ClinicalTrials.gov და EU CTR ბაზებში\n3. მოამზადებს შესაფერისი კვლევების სიას ქართულად\n4. დაგიკავშირდებათ ვარიანტების განსახილველად",
        telegramTitle: "გამოიწერეთ ჩვენი არხი",
        telegramDesc: "ყოველკვირეული მიმოხილვები ახალი კვლევების შესახებ",
        telegramBtn: "გახსენი @medgzuri",
        telegramLink: "https://t.me/medgzuri",
      },
    },
  },

  en: {
    name: "MedPath",
    tagline: "We find the path to your child's treatment",
    taglineSub: "Medical navigation for families facing rare and severe diagnoses",
    colors: {
      primary: "#1B4F72",
      primaryHover: "#134074",
      accent: "#2ECC71",
      accentHover: "#27AE60",
      bg: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#1A202C",
      textMuted: "#718096",
      border: "#E2E8F0",
      hero: "linear-gradient(135deg, #1B4F72 0%, #2C3E50 50%, #1A202C 100%)",
    },
    fonts: {
      heading: "'Source Sans 3', 'Inter', sans-serif",
      body: "'Noto Sans', 'Inter', sans-serif",
    },
    cta: {
      primary: "Get started",
      secondary: "Learn more",
      contact: "Contact us",
    },
    hero: {
      badge: "Medical Navigation",
      headline: "Your doctor said \"nothing can be done\"?\nWe know where to look.",
      sub: "50+ outreach attempts. 12+ programs found. 3 continents. Real experience, not theory.",
      btnPrimary: "Get started",
      btnSecondary: "Learn more",
      stats: [
        { number: "50+", label: "Outreach attempts" },
        { number: "12+", label: "Programs found" },
        { number: "3", label: "Continents" },
      ],
    },
    values: [
      { icon: "🎯", title: "Clinical trial matching", desc: "We find trials on ClinicalTrials.gov and EU CTR that match your child's condition" },
      { icon: "📧", title: "Direct physician outreach", desc: "We draft emails to leading researchers and clinicians using proven methodology" },
      { icon: "💰", title: "Financial navigation", desc: "Grants, foundations, charitable programs — we find ways to cover treatment costs" },
    ],
    services: {
      label: "Services",
      title: "What we offer",
      subtitle: "Choose the level of support that fits your family — from self-guided to full concierge",
      items: [
        { icon: "📦", title: "Advocacy Toolkit", price: "$97", desc: "Email templates, trial search guide, contact tracker, financial aid directory" },
        { icon: "🤖", title: "AI Navigator", price: "$197/mo", desc: "AI-powered trial matching, eligibility screening, personalized outreach emails" },
        { icon: "🌐", title: "Concierge Navigation", price: "$2,000+", desc: "Full-service: research, clinic communication, logistics, and follow-up" },
      ],
    },
    steps: {
      label: "Process",
      title: "Three simple steps",
      subtitle: "Start today and receive your first results within 24 hours",
      items: [
        { title: "Tell us your story", desc: "Complete a brief intake form — diagnosis, age, treatments tried" },
        { title: "We search", desc: "AI + human experts search trials, programs, and clinics across 3 continents" },
        { title: "Get your plan", desc: "Personalized report with options, estimated costs, and next steps" },
      ],
    },
    trust: "95-day campaign • 50+ outreach attempts • 24% success rate • 12+ programs secured",
    contact: {
      label: "Contact",
      title: "Start your search today",
      description: "Write to us and we'll help you choose the right service for your family",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Messenger",
      linkWhatsapp: "995555145719",
      linkFacebook: "61587738421431",
      form: {
        name: "Name *",
        namePlaceholder: "Your name",
        phone: "Phone *",
        phonePlaceholder: "+1 (XXX) XXX-XXXX",
        email: "Email",
        emailPlaceholder: "your@email.com",
        message: "Message *",
        messagePlaceholder: "Tell us about your situation...",
        submit: "📨 Send",
        successTitle: "Thank you!",
        successText: "Your message has been received. We'll respond within 24 hours.",
      },
    },
    nav: {
      search: "Search",
      services: "Services",
      process: "Process",
      contact: "Contact",
      intake: "Intake Form",
      searchPlaceholder: "Search is active",
    },
    searchQueries: [
      "lung cancer treatment trials",
      "type 2 diabetes clinical research",
      "pediatric epilepsy treatment programs",
      "oncology clinics in Europe",
      "rare disease clinical trials",
      "cardiac rehabilitation options",
    ],
    footer: {
      copyright: "© 2026 MedPath by Med&გზური",
      disclaimer: "This is an informational service, not medical advice. All decisions should be made in consultation with your healthcare provider.",
    },
    social: {
      telegram: "https://t.me/medpath_nav",
      facebook: "https://facebook.com/medpath",
    },
    locale: "en-US",
    dir: "ltr",
    intake: {
      pageTitle: "Free consultation",
      badge: "FREE · 10 days left",
      steps: [
        { id: "intro", label: "Start" },
        { id: "child", label: "Child" },
        { id: "medical", label: "Diagnosis" },
        { id: "goals", label: "Goals" },
        { id: "survey", label: "Survey" },
        { id: "contact", label: "Contact" },
        { id: "done", label: "Done" },
      ],
      progress: { step: "Step", of: "of" },
      nav: { back: "← Back", next: "Next →", start: "Start filling out →", submit: "Submit ✓" },
      intro: {
        title: "We'll find clinical trials for your child",
        desc: "Fill out the form in 3 minutes — we'll match suitable treatment programs and research worldwide, free of charge",
        howTitle: "How it works:",
        howSteps: "1. You fill out a form about your child (3 min)\n2. We match suitable trials and programs (1–3 days)\n3. You receive a list with descriptions in your language",
        howNote: "Based on real experience — 7 months navigating clinics in the US and Europe",
        stats: [
          { n: "50+", t: "physician outreach" },
          { n: "12+", t: "programs found" },
          { n: "24%", t: "success rate" },
        ],
      },
      child: {
        title: "About your child",
        subtitle: "Basic information to match clinical trials",
        nameLabel: "Child's name (optional)",
        namePlaceholder: "Name",
        ageLabel: "Child's age *",
        ageUnits: ["months", "years"],
        countryLabel: "Country of residence *",
        countries: ["United States", "United Kingdom", "Germany", "France", "Israel", "Turkey", "Georgia", "Canada", "Australia", "Other country"],
        otherCountryPlaceholder: "Specify country",
      },
      diagnosis: {
        title: "Diagnosis",
        subtitle: "Select one or more",
        items: [
          { id: "cp", label: "Cerebral palsy (CP)" },
          { id: "hie", label: "Hypoxic-ischemic encephalopathy (HIE)" },
          { id: "epilepsy", label: "Epilepsy" },
          { id: "genetic", label: "Genetic disorder" },
          { id: "oncology", label: "Pediatric oncology" },
          { id: "cardiology", label: "Congenital heart defect" },
          { id: "rare", label: "Rare (orphan) disease" },
          { id: "neuromuscular", label: "Neuromuscular disease (SMA, DMD)" },
          { id: "autism", label: "Autism spectrum disorder (ASD)" },
          { id: "other", label: "Other" },
        ],
        otherPlaceholder: "Specify diagnosis",
        detailsLabel: "Brief description of child's condition",
        detailsPlaceholder: "E.g.: child cannot hold head, has seizures, MRI showed...",
        treatmentLabel: "What treatments have been tried?",
        treatmentPlaceholder: "Rehabilitation, medications, surgeries...",
        mriLabel: "Are brain MRI results available?",
        mriOptions: ["Yes", "No", "Not sure"],
      },
      goals: {
        title: "What are you looking for?",
        subtitle: "Select all that apply",
        items: [
          { id: "clinical_trials", label: "Find a clinical trial (free treatment)" },
          { id: "rehab", label: "Find a specialized rehabilitation center" },
          { id: "second_opinion", label: "Get a second opinion from a foreign doctor" },
          { id: "experimental", label: "Find experimental therapy (stem cells, etc.)" },
          { id: "financial", label: "Find financial aid or grants" },
          { id: "documents", label: "Help with documents and communication in English" },
          { id: "travel", label: "Organize a medical travel trip" },
        ],
        otherLabel: "Anything else? (optional)",
        otherPlaceholder: "Other needs...",
      },
      survey: {
        title: "One question",
        subtitle: "Help us understand the value of this service",
        question: "Imagine a specialist finds clinical trials matching your child, prepares medical documents in English, drafts letters to doctors, and supports the entire communication process. How much would you be willing to pay for such a service?",
        ranges: [
          { value: "0", label: "Free (not ready to pay)" },
          { value: "50-150", label: "$50 – $150" },
          { value: "150-500", label: "$150 – $500" },
          { value: "500-1000", label: "$500 – $1,000" },
          { value: "1000-3000", label: "$1,000 – $3,000" },
          { value: "3000+", label: "$3,000+" },
        ],
        valueLabel: "What would be most valuable to you? (optional)",
        valuePlaceholder: "E.g.: help translating documents, finding grants, connecting with doctors...",
        sourceLabel: "How did you hear about MedPath?",
        sources: ["Facebook", "Instagram", "YouTube", "Friends/family", "Google Search", "Other"],
      },
      contact: {
        title: "Contact information",
        subtitle: "Where should we send the results?",
        nameLabel: "Your name *",
        namePlaceholder: "Full name",
        emailLabel: "Email",
        emailPlaceholder: "email@example.com",
        phoneLabel: "Phone (WhatsApp)",
        phonePlaceholder: "+1...",
        messengerLabel: "Messenger / Facebook",
        messengerPlaceholder: "Facebook profile link or name",
        preferLabel: "Preferred contact method",
        preferOptions: [
          { v: "whatsapp", l: "WhatsApp" },
          { v: "messenger", l: "Messenger" },
          { v: "email", l: "Email" },
        ],
        consent: "I consent to data processing for clinical trial matching purposes. Data is used solely for this purpose and is not shared with third parties. *",
      },
      done: {
        title: "Application submitted!",
        message: "We'll match suitable clinical trials and programs within 1–3 business days and contact you via",
        nextTitle: "What's next:",
        nextSteps: "1. Our specialist reviews your intake form\n2. Searches ClinicalTrials.gov and EU CTR databases\n3. Prepares a list of matching trials in your language\n4. Contacts you to discuss options",
        telegramTitle: "Subscribe to our channel",
        telegramDesc: "Weekly reviews of new clinical trials",
        telegramBtn: "Open @medpath_nav",
        telegramLink: "https://t.me/medpath_nav",
      },
    },
  },

  ru: {
    name: "МедПуть",
    tagline: "Находим путь к лечению вашего ребёнка",
    taglineSub: "Медицинская навигация для семей с тяжёлыми и редкими диагнозами",
    colors: {
      primary: "#134074",
      primaryHover: "#0B2545",
      accent: "#48C7B0",
      accentHover: "#1D9E75",
      bg: "#FAFCFD",
      surface: "#EDF5FA",
      text: "#0B2545",
      textMuted: "#4A6D8C",
      border: "#D6EBF5",
      hero: "linear-gradient(135deg, #0B2545 0%, #134074 40%, #1B6B93 100%)",
    },
    fonts: {
      heading: "'Source Sans 3', 'Noto Sans', sans-serif",
      body: "'Noto Sans', sans-serif",
    },
    cta: {
      primary: "Начать сейчас",
      secondary: "Узнать больше",
      contact: "Связаться с нами",
    },
    hero: {
      badge: "Медицинская навигация",
      headline: "Врач сказал «ничего нельзя сделать»?\nМы знаем, куда обратиться.",
      sub: "50+ обращений. 12+ программ. 3 континента. Реальный опыт, а не теория.",
      btnPrimary: "Начать сейчас",
      btnSecondary: "Узнать больше",
      stats: [
        { number: "50+", label: "Обращений" },
        { number: "12+", label: "Программ" },
        { number: "3", label: "Континента" },
      ],
    },
    values: [
      { icon: "🎯", title: "Клинические исследования", desc: "Находим исследования на ClinicalTrials.gov и EU CTR, подходящие вашему ребёнку" },
      { icon: "📧", title: "Прямая связь с врачами", desc: "Составляем письма ведущим исследователям по проверенной методологии" },
      { icon: "💰", title: "Финансовая навигация", desc: "Гранты, фонды, благотворительные программы — находим способы покрыть расходы на лечение" },
    ],
    services: {
      label: "Услуги",
      title: "Что мы предлагаем",
      subtitle: "Выберите уровень поддержки — от набора инструментов до полного сопровождения",
      items: [
        { icon: "📦", title: "Набор инструментов", price: "$97", desc: "Шаблоны писем, инструкция по поиску исследований, трекер контактов, каталог финансовой помощи" },
        { icon: "🤖", title: "AI-Навигатор", price: "$197/мес", desc: "ИИ-подбор клинических исследований, проверка критериев участия, генерация писем врачам" },
        { icon: "🌐", title: "Персональная навигация", price: "$2 000+", desc: "Полный сервис: поиск, коммуникация с клиниками, логистика, сопровождение" },
      ],
    },
    steps: {
      label: "Процесс",
      title: "Три простых шага",
      subtitle: "Начните сегодня и получите первые результаты в течение 24 часов",
      items: [
        { title: "Расскажите о себе", desc: "Заполните краткую анкету — диагноз, возраст, что пробовали" },
        { title: "Мы ищем", desc: "ИИ + эксперт ищут исследования, программы и клиники на 3 континентах" },
        { title: "Получите план", desc: "Персонализированный отчёт: варианты, стоимость, следующие шаги" },
      ],
    },
    trust: "95 дней кампании • 50+ обращений • 24% успешность • 12+ программ",
    contact: {
      label: "Контакт",
      title: "Начните поиск сегодня",
      description: "Напишите нам, и мы поможем подобрать подходящую услугу для вашей семьи",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Telegram",
      linkWhatsapp: "995555145719",
      linkTelegram: "https://t.me/medput",
      linkFacebook: "61587738421431",
      form: {
        name: "Имя *",
        namePlaceholder: "Ваше имя",
        phone: "Телефон *",
        phonePlaceholder: "+7 (XXX) XXX-XX-XX",
        email: "Эл. почта",
        emailPlaceholder: "your@email.com",
        message: "Сообщение *",
        messagePlaceholder: "Расскажите о вашей ситуации...",
        submit: "📨 Отправить",
        successTitle: "Спасибо!",
        successText: "Ваше сообщение получено. Мы ответим в течение 24 часов.",
      },
    },
    nav: {
      search: "Поиск",
      services: "Услуги",
      process: "Процесс",
      contact: "Контакт",
      intake: "Анкета",
      searchPlaceholder: "Поиск активен",
    },
    searchQueries: [
      "лечение рака лёгких",
      "клинические исследования диабета 2 типа",
      "программы лечения детской эпилепсии",
      "онкологические клиники в Европе",
      "клинические исследования редких заболеваний",
      "варианты кардиореабилитации",
    ],
    footer: {
      copyright: "© 2026 МедПуть | Med&გзური",
      disclaimer: "Это информационный сервис, а не медицинская консультация. Все решения принимайте совместно с вашим лечащим врачом.",
    },
    social: {
      telegram: "https://t.me/medput",
      facebook: "https://facebook.com/groups/medput",
    },
    locale: "ru-RU",
    dir: "ltr",
    intake: {
      pageTitle: "Бесплатная консультация",
      badge: "БЕСПЛАТНО · осталось 10 дней",
      steps: [
        { id: "intro", label: "Начало" },
        { id: "child", label: "О ребёнке" },
        { id: "medical", label: "Диагноз" },
        { id: "goals", label: "Цели" },
        { id: "survey", label: "Опрос" },
        { id: "contact", label: "Контакты" },
        { id: "done", label: "Готово" },
      ],
      progress: { step: "Шаг", of: "из" },
      nav: { back: "← Назад", next: "Далее →", start: "Начать заполнение →", submit: "Отправить заявку ✓" },
      intro: {
        title: "Найдём клинические исследования для вашего ребёнка",
        desc: "Заполните анкету за 3 минуты — мы бесплатно подберём подходящие программы лечения и исследования по всему миру",
        howTitle: "Как это работает:",
        howSteps: "1. Вы заполняете анкету о ребёнке (3 мин)\n2. Мы подбираем подходящие исследования (1-3 дня)\n3. Вы получаете список с описанием на вашем языке",
        howNote: "Основано на реальном опыте — 7 месяцев навигации по клиникам США и Европы",
        stats: [
          { n: "50+", t: "обращений к врачам" },
          { n: "12+", t: "программ найдено" },
          { n: "24%", t: "успешность" },
        ],
      },
      child: {
        title: "О вашем ребёнке",
        subtitle: "Основная информация для подбора исследований",
        nameLabel: "Имя ребёнка (необязательно)",
        namePlaceholder: "Имя",
        ageLabel: "Возраст ребёнка *",
        ageUnits: ["месяцев", "лет"],
        countryLabel: "Страна проживания *",
        countries: ["Казахстан", "Узбекистан", "Кыргызстан", "Украина", "Грузия", "Армения", "Молдова", "Таджикистан", "Россия", "Израиль", "Германия", "США", "Франция", "Турция", "Другая страна"],
        otherCountryPlaceholder: "Укажите страну",
      },
      diagnosis: {
        title: "Диагноз",
        subtitle: "Выберите один или несколько",
        items: [
          { id: "cp", label: "ДЦП (детский церебральный паралич)" },
          { id: "hie", label: "ГИЭ (гипоксически-ишемическая энцефалопатия)" },
          { id: "epilepsy", label: "Эпилепсия" },
          { id: "genetic", label: "Генетическое заболевание" },
          { id: "oncology", label: "Онкология (детская)" },
          { id: "cardiology", label: "Кардиология (врождённый порок сердца)" },
          { id: "rare", label: "Редкое (орфанное) заболевание" },
          { id: "neuromuscular", label: "Нейромышечное заболевание (SMA, DMD)" },
          { id: "autism", label: "Аутизм / РАС" },
          { id: "other", label: "Другое" },
        ],
        otherPlaceholder: "Укажите диагноз",
        detailsLabel: "Краткое описание состояния ребёнка",
        detailsPlaceholder: "Например: ребёнок не держит голову, есть судороги, MRI показало...",
        treatmentLabel: "Какое лечение уже пробовали?",
        treatmentPlaceholder: "Реабилитация, лекарства, операции...",
        mriLabel: "Есть ли результаты МРТ головного мозга?",
        mriOptions: ["Да, есть", "Нет", "Не уверен(а)"],
      },
      goals: {
        title: "Что вы ищете?",
        subtitle: "Выберите всё, что актуально",
        items: [
          { id: "clinical_trials", label: "Найти клиническое исследование (бесплатное лечение)" },
          { id: "rehab", label: "Найти специализированный центр реабилитации" },
          { id: "second_opinion", label: "Получить второе мнение от зарубежного врача" },
          { id: "experimental", label: "Найти экспериментальную терапию (стволовые клетки и др.)" },
          { id: "financial", label: "Найти финансовую помощь / гранты" },
          { id: "documents", label: "Помощь с документами и коммуникацией на английском" },
          { id: "travel", label: "Организация поездки на лечение" },
        ],
        otherLabel: "Что-то ещё? (необязательно)",
        otherPlaceholder: "Другие потребности...",
      },
      survey: {
        title: "Один вопрос",
        subtitle: "Помогите нам понять ценность этого сервиса",
        question: "Представьте, что специалист находит для вашего ребёнка подходящие клинические исследования, готовит медицинские документы на английском, составляет письма врачам и сопровождает весь процесс коммуникации. Сколько вы были бы готовы заплатить за такой сервис?",
        ranges: [
          { value: "0", label: "Бесплатно (не готов платить)" },
          { value: "50-150", label: "$50 – $150" },
          { value: "150-500", label: "$150 – $500" },
          { value: "500-1000", label: "$500 – $1 000" },
          { value: "1000-3000", label: "$1 000 – $3 000" },
          { value: "3000+", label: "$3 000+" },
        ],
        valueLabel: "Что было бы самым ценным для вас? (необязательно)",
        valuePlaceholder: "Например: помощь с переводом документов, поиск грантов, связь с врачами...",
        sourceLabel: "Как вы узнали о МедПуть?",
        sources: ["Telegram", "Facebook", "Instagram", "YouTube", "Друзья/знакомые", "Поиск Google", "Другое"],
      },
      contact: {
        title: "Контактные данные",
        subtitle: "Куда отправить результаты подбора?",
        nameLabel: "Ваше имя *",
        namePlaceholder: "Имя и фамилия",
        emailLabel: "Эл. почта",
        emailPlaceholder: "email@example.com",
        phoneLabel: "Телефон (WhatsApp)",
        phonePlaceholder: "+7...",
        messengerLabel: "Telegram (username или номер)",
        messengerPlaceholder: "@username или +7...",
        preferLabel: "Предпочитаемый способ связи",
        preferOptions: [
          { v: "telegram", l: "Telegram" },
          { v: "whatsapp", l: "WhatsApp" },
          { v: "email", l: "Email" },
        ],
        consent: "Я даю согласие на обработку данных для подбора клинических исследований. Данные используются исключительно для этой цели и не передаются третьим лицам. *",
      },
      done: {
        title: "Заявка отправлена!",
        message: "Мы подберём подходящие клинические исследования и программы в течение 1-3 рабочих дней и свяжемся с вами через",
        nextTitle: "Что дальше:",
        nextSteps: "1. Наш специалист изучит вашу анкету\n2. Проведёт поиск по базам ClinicalTrials.gov и EU CTR\n3. Подготовит список подходящих исследований на русском языке\n4. Свяжется с вами для обсуждения вариантов",
        telegramTitle: "Подпишитесь на наш Telegram-канал",
        telegramDesc: "Еженедельные обзоры новых исследований",
        telegramBtn: "Открыть @medput",
        telegramLink: "https://t.me/medput",
      },
    },
    extraSections: {
      countries: {
        title: "Мы помогаем семьям из:",
        list: ["Казахстан", "Узбекистан", "Украина", "Грузия", "Армения", "Кыргызстан", "Молдова", "Израиль (рус.)", "Германия (рус.)", "США (рус.)"],
      },
      whyUs: {
        title: "Почему МедПуть?",
        points: [
          { icon: "🎯", title: "Клинические исследования", desc: "Находим исследования на ClinicalTrials.gov и EU CTR, подходящие вашему ребёнку" },
          { icon: "📧", title: "Прямая связь с врачами", desc: "Составляем письма ведущим исследователям по проверенной методологии" },
          { icon: "💰", title: "Финансовая навигация", desc: "Гранты, фонды, благотворительные программы — находим способы покрыть расходы" },
          { icon: "🌍", title: "3 континента", desc: "США, Европа, Азия — знаем систему изнутри" },
        ],
      },
    },
  },
};

// Export for both module and script contexts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { brandConfig };
}
