/**
 * brand-config.js — Trilingual brand configuration for MED&გზური / MedPath / МедПуть
 * Each language has its own visual identity, tone, and content.
 */
const brandConfig = {
  ka: {
    name: "Med&გზური",
    tagline: "ვპოულობთ გზას შენი შვილის მკურნალობისკენ",
    taglineSub: "სამედიცინო ნავიგაცია ოჯახებისთვის",
    colors: {
      primary: "#8B1A1A",
      primaryHover: "#6B1414",
      accent: "#D4A843",
      accentHover: "#B8922E",
      bg: "#FFFDF7",
      surface: "#F5F0E8",
      text: "#2C1810",
      textMuted: "#6B5D52",
      border: "#D9CFC2",
      hero: "linear-gradient(135deg, #8B1A1A 0%, #5C1010 50%, #2C1810 100%)",
    },
    fonts: {
      heading: "'BPG Nino Mtavruli', 'Noto Sans Georgian', sans-serif",
      body: "'Noto Sans Georgian', sans-serif",
    },
    cta: {
      primary: "დაიწყე ახლა",
      secondary: "გაიგე მეტი",
      contact: "დაგვიკავშირდი",
    },
    hero: {
      badge: "სამედიცინო ნავიგაცია",
      headline: "ექიმი ამბობს \u201Eვერაფერს ვიზამთ\u201C?\nჩვენ ვიცით სად მივმართოთ.",
      sub: "50+ მოთხოვნა. 12+ პროგრამა. 3 კონტინენტი. რეალური გამოცდილება.",
      btnPrimary: "დაიწყე ახლა",
      btnSecondary: "გაიგე მეტი",
      stats: [
        { number: "50+", label: "მოთხოვნა" },
        { number: "12+", label: "პროგრამა" },
        { number: "3", label: "კონტინენტი" },
      ],
    },
    values: [
      { icon: "🌍", title: "ენის ბარიერი აღარ არსებობს", desc: "38 მილიონი სამედიცინო კვლევა ახლა ქართულად ხელმისაწვდომია" },
      { icon: "🔍", title: "იპოვე ის, რაც Google-ში ვერ იპოვე", desc: "PubMed, კლინიკური კვლევები, ევროპული კლინიკები — ერთი ძიებით" },
      { icon: "💰", title: "₾149-დან — არა ათასობით", desc: "საერთაშორისო დონის ინფორმაცია, ქართული ფასით" },
    ],
    services: {
      label: "სერვისები",
      title: "რას გთავაზობთ",
      subtitle: "აირჩიეთ თქვენზე მორგებული სერვისი — ძიებიდან სრულ კოორდინაციამდე",
      items: [
        { icon: "📦", title: "ტულკითი", price: "₾149", desc: "ელ-ფოსტის შაბლონები, trial ძიების ინსტრუქცია, კონტაქტების ტრეკერი" },
        { icon: "🤖", title: "AI ნავიგატორი", price: "₾497/თვე", desc: "AI-ით clinical trials მოძიება, eligibility შემოწმება, ელ-ფოსტის გენერაცია" },
        { icon: "🌐", title: "პირადი ნავიგაცია", price: "₾5,000+", desc: "სრული concierge სერვისი — ძიება, კომუნიკაცია, ლოჯისტიკა" },
      ],
    },
    steps: {
      label: "პროცესი",
      title: "სამი მარტივი ნაბიჯი",
      subtitle: "დაიწყეთ დღეს და 24 საათში მიიღეთ პირველი შედეგები",
      items: [
        { title: "მოგვიყევით", desc: "შეავსეთ მოკლე ანკეტა — დიაგნოზი, ასაკი, რა სცადეთ" },
        { title: "ჩვენ ვეძებთ", desc: "AI + ადამიანი ეძებს trials, პროგრამებს, კლინიკებს 3 კონტინენტზე" },
        { title: "მიიღეთ გეგმა", desc: "პერსონალიზებული ანგარიში: ვარიანტები, ფასები, შემდეგი ნაბიჯები" },
      ],
    },
    trust: "95-დღიანი კამპანია • 50+ მოთხოვნა • 24% წარმატების მაჩვენებელი",
    contact: {
      label: "კონტაქტი",
      title: "დაიწყეთ ძიება დღეს",
      description: "გვწერეთ და დაგეხმარებით თქვენთვის სწორი სერვისის შერჩევაში",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Messenger",
      linkWhatsapp: "995555145719",
      linkFacebook: "61587738421431",
      form: {
        name: "სახელი *",
        namePlaceholder: "თქვენი სახელი",
        phone: "ტელეფონი *",
        phonePlaceholder: "+995 5XX XXX XXX",
        email: "Email",
        emailPlaceholder: "your@email.com",
        message: "შეტყობინება *",
        messagePlaceholder: "მოგვიყევით თქვენი კითხვა...",
        submit: "📨 გაგზავნა",
        successTitle: "გმადლობთ!",
        successText: "თქვენი შეტყობინება მიღებულია.",
      },
    },
    nav: {
      search: "ძიება",
      services: "სერვისები",
      process: "პროცესი",
      contact: "კონტაქტი",
      searchPlaceholder: "ძიება აქტიურია",
    },
    searchQueries: [
      "ფილტვის კიბოს მკურნალობა",
      "ტიპი 2 დიაბეტის კვლევები",
      "ჰიპერტენზიის თანამედროვე მიდგომები",
      "ონკოლოგიური კლინიკები ევროპაში",
      "ეპილეფსიის ახალი წამლები",
      "კარდიოლოგიური რეაბილიტაცია",
    ],
    footer: {
      copyright: "© 2026 Med&გზური",
      disclaimer: "ეს არის საინფორმაციო სერვისი, არა სამედიცინო კონსულტაცია.",
    },
    social: {
      telegram: "https://t.me/medgzuri",
      facebook: "https://facebook.com/medgzuri",
    },
    locale: "ka-GE",
    dir: "ltr",
  },

  en: {
    name: "MedPath",
    tagline: "We find the path to your child's treatment",
    taglineSub: "Medical navigation for families with rare & severe diagnoses",
    colors: {
      primary: "#1B4F72",
      primaryHover: "#134074",
      accent: "#2ECC71",
      accentHover: "#27AE60",
      bg: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#1A202C",
      textMuted: "#718096",
      border: "#E2E8F0",
      hero: "linear-gradient(135deg, #1B4F72 0%, #2C3E50 50%, #1A202C 100%)",
    },
    fonts: {
      heading: "'Source Sans 3', 'Inter', sans-serif",
      body: "'Noto Sans', 'Inter', sans-serif",
    },
    cta: {
      primary: "Get started",
      secondary: "Learn more",
      contact: "Contact us",
    },
    hero: {
      badge: "Medical Navigation",
      headline: "Your doctor said \"nothing can be done\"?\nWe know where to look.",
      sub: "50+ outreach attempts. 12+ programs. 3 continents. Real experience, not theory.",
      btnPrimary: "Get started",
      btnSecondary: "Learn more",
      stats: [
        { number: "50+", label: "Outreach attempts" },
        { number: "12+", label: "Programs found" },
        { number: "3", label: "Continents" },
      ],
    },
    values: [
      { icon: "🎯", title: "Clinical Trials", desc: "We find trials on ClinicalTrials.gov and EU CTR that match your child" },
      { icon: "📧", title: "Direct doctor outreach", desc: "We draft emails to leading researchers using proven methodology" },
      { icon: "💰", title: "Financial navigation", desc: "Grants, foundations, charity care — we find ways to cover costs" },
    ],
    services: {
      label: "Services",
      title: "What we offer",
      subtitle: "Choose the level of support that fits your family — from DIY to full concierge",
      items: [
        { icon: "📦", title: "Advocacy Toolkit", price: "$97", desc: "Email templates, trial search guide, contact tracker, financial aid directory" },
        { icon: "🤖", title: "AI Navigator", price: "$197/mo", desc: "AI-powered trial matching, eligibility check, personalized outreach emails" },
        { icon: "🌐", title: "Concierge Navigation", price: "$2,000+", desc: "Full-service: search, communication, logistics, follow-up" },
      ],
    },
    steps: {
      label: "Process",
      title: "Three simple steps",
      subtitle: "Start today and get your first results within 24 hours",
      items: [
        { title: "Tell us your story", desc: "Fill out a brief form — diagnosis, age, what you've tried" },
        { title: "We search", desc: "AI + human experts search trials, programs, clinics across 3 continents" },
        { title: "Get your plan", desc: "Personalized report: options, costs, next steps" },
      ],
    },
    trust: "95-day campaign • 50+ requests • 24% success rate • 12+ programs secured",
    contact: {
      label: "Contact",
      title: "Start your search today",
      description: "Write to us and we'll help you choose the right service",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Messenger",
      linkWhatsapp: "995555145719",
      linkFacebook: "61587738421431",
      form: {
        name: "Name *",
        namePlaceholder: "Your name",
        phone: "Phone *",
        phonePlaceholder: "+1 (XXX) XXX-XXXX",
        email: "Email",
        emailPlaceholder: "your@email.com",
        message: "Message *",
        messagePlaceholder: "Tell us about your situation...",
        submit: "📨 Send",
        successTitle: "Thank you!",
        successText: "Your message has been received.",
      },
    },
    nav: {
      search: "Search",
      services: "Services",
      process: "Process",
      contact: "Contact",
      searchPlaceholder: "Search is active",
    },
    searchQueries: [
      "lung cancer treatment trials",
      "type 2 diabetes research",
      "pediatric epilepsy programs",
      "oncology clinics in Europe",
      "rare disease clinical trials",
      "cardiac rehabilitation options",
    ],
    footer: {
      copyright: "© 2026 MedPath by Med&გზური",
      disclaimer: "This is an informational service, not medical advice. All decisions should be made with your healthcare team.",
    },
    social: {
      telegram: "https://t.me/medpath_nav",
      facebook: "https://facebook.com/medpath",
    },
    locale: "en-US",
    dir: "ltr",
  },

  ru: {
    name: "МедПуть",
    tagline: "Находим путь к лечению вашего ребёнка",
    taglineSub: "Медицинская навигация для семей с тяжёлыми диагнозами",
    colors: {
      primary: "#134074",
      primaryHover: "#0B2545",
      accent: "#48C7B0",
      accentHover: "#1D9E75",
      bg: "#FAFCFD",
      surface: "#EDF5FA",
      text: "#0B2545",
      textMuted: "#4A6D8C",
      border: "#D6EBF5",
      hero: "linear-gradient(135deg, #0B2545 0%, #134074 40%, #1B6B93 100%)",
    },
    fonts: {
      heading: "'Source Sans 3', 'Noto Sans', sans-serif",
      body: "'Noto Sans', sans-serif",
    },
    cta: {
      primary: "Начать сейчас",
      secondary: "Узнать больше",
      contact: "Связаться с нами",
    },
    hero: {
      badge: "Медицинская навигация",
      headline: "Врач сказал «ничего нельзя сделать»?\nМы знаем, куда обратиться.",
      sub: "50+ обращений. 12+ программ. 3 континента. Реальный опыт, а не теория.",
      btnPrimary: "Начать сейчас",
      btnSecondary: "Узнать больше",
      stats: [
        { number: "50+", label: "Обращений" },
        { number: "12+", label: "Программ" },
        { number: "3", label: "Континента" },
      ],
    },
    values: [
      { icon: "🎯", title: "Клинические исследования", desc: "Находим trials на ClinicalTrials.gov и EU CTR, которые подходят вашему ребёнку" },
      { icon: "📧", title: "Прямая связь с врачами", desc: "Составляем письма ведущим исследователям по проверенной методологии" },
      { icon: "💰", title: "Финансовая навигация", desc: "Гранты, фонды, charity care — находим способы покрыть расходы" },
    ],
    services: {
      label: "Услуги",
      title: "Что мы предлагаем",
      subtitle: "Выберите уровень поддержки — от набора инструментов до полного сопровождения",
      items: [
        { icon: "📦", title: "Набор инструментов", price: "$97", desc: "Шаблоны писем, инструкция поиска исследований, трекер контактов, каталог финпомощи" },
        { icon: "🤖", title: "AI-Навигатор", price: "$197/мес", desc: "ИИ-подбор клинических исследований, проверка критериев, генерация писем врачам" },
        { icon: "🌐", title: "Персональная навигация", price: "$2 000+", desc: "Полный сервис: поиск, коммуникация с клиниками, логистика, сопровождение" },
      ],
    },
    steps: {
      label: "Процесс",
      title: "Три простых шага",
      subtitle: "Начните сегодня и получите первые результаты в течение 24 часов",
      items: [
        { title: "Расскажите о себе", desc: "Заполните краткую анкету — диагноз, возраст, что пробовали" },
        { title: "Мы ищем", desc: "ИИ + эксперт ищут trials, программы, клиники на 3 континентах" },
        { title: "Получите план", desc: "Персонализированный отчёт: варианты, стоимость, следующие шаги" },
      ],
    },
    trust: "95 дней кампании • 50+ обращений • 24% успешность • 12+ программ",
    contact: {
      label: "Контакт",
      title: "Начните поиск сегодня",
      description: "Напишите нам, и мы поможем выбрать подходящую услугу",
      btnWhatsapp: "WhatsApp",
      btnFacebook: "Telegram",
      linkWhatsapp: "995555145719",
      linkTelegram: "https://t.me/medput",
      linkFacebook: "61587738421431",
      form: {
        name: "Имя *",
        namePlaceholder: "Ваше имя",
        phone: "Телефон *",
        phonePlaceholder: "+7 (XXX) XXX-XX-XX",
        email: "Email",
        emailPlaceholder: "your@email.com",
        message: "Сообщение *",
        messagePlaceholder: "Расскажите о вашей ситуации...",
        submit: "📨 Отправить",
        successTitle: "Спасибо!",
        successText: "Ваше сообщение получено.",
      },
    },
    nav: {
      search: "Поиск",
      services: "Услуги",
      process: "Процесс",
      contact: "Контакт",
      searchPlaceholder: "Поиск активен",
    },
    searchQueries: [
      "лечение рака лёгких",
      "исследования диабета 2 типа",
      "детская эпилепсия программы",
      "онкологические клиники в Европе",
      "редкие заболевания клинические исследования",
      "кардиореабилитация варианты",
    ],
    footer: {
      copyright: "© 2026 МедПуть | Med&გзური",
      disclaimer: "Это информационный сервис, а не медицинская консультация. Все решения принимайте совместно с вашим лечащим врачом.",
    },
    social: {
      telegram: "https://t.me/medput",
      facebook: "https://facebook.com/groups/medput",
    },
    locale: "ru-RU",
    dir: "ltr",
    extraSections: {
      countries: {
        title: "Мы помогаем семьям из:",
        list: ["Казахстан", "Узбекистан", "Украина", "Грузия", "Армения", "Кыргызстан", "Молдова", "Израиль (рус.)", "Германия (рус.)", "США (рус.)"],
      },
      whyUs: {
        title: "Почему МедПуть?",
        points: [
          { icon: "🎯", title: "Клинические исследования", desc: "Находим trials на ClinicalTrials.gov и EU CTR, которые подходят вашему ребёнку" },
          { icon: "📧", title: "Прямая связь с врачами", desc: "Составляем письма ведущим исследователям по проверенной методологии" },
          { icon: "💰", title: "Финансовая навигация", desc: "Гранты, фонды, charity care — находим способы покрыть расходы" },
          { icon: "🌍", title: "3 континента", desc: "США, Европа, Азия — знаем систему изнутри" },
        ],
      },
    },
  },
};

// Export for both module and script contexts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { brandConfig };
}
